### ISSUE TITLE
Проблема с выбором Категория

### ISSUE THREAD

**Issue by Ravshon** [DLEPremium/kinopoisk-parser-dle-v2#1]
Проблема с выбором Категория

![image](https://github.com/DLEPremium/kinopoisk-parser-dle-v2/assets/70154833/ecdd79aa-3183-4d10-a297-05038a780577)
У меня такой настройка!

![image](https://github.com/DLEPremium/kinopoisk-parser-dle-v2/assets/70154833/a5da117d-0faf-4eae-a1a0-40a26e1aa842)
Когда я парсу проста не вибирается категория!

**Comment by DLEPremium** [comment]
Привет. У вас указано в настройках две категории - фантастика и фэнтези. Это не совсем правильно, так как это абсолютно разные жанры. Нужно под каждый своя категория. При текущих настройках модуль назначит категорию только если у фильма/сериала есть оба эти жанры, и фантастика и фэнтези одновременно

**Comment by Ravshon** [comment]
Все да я решиль!
